# Ordinary Differential Equations

Chapter 8 of the texbook.

In this module we will develop numerical methods for solving ***the initial value problem (IVP) for ordinary differential equations (ODEs)***

$$
    \frac{d}{dt} {\bf y}(t) = {\bf f}({\bf y}(t), t), \qquad
    {\bf y}(t_0) = {\bf y}_0.
$$

### Example: A harmonic oscillator 
$$
    \frac{d^2}{dt^2} x(t) = -\omega^2 x(t), \qquad x(0)=1, \qquad \frac{d}{dt} x(0) = 0.
$$
The exact solution $x(t) = \cos(\omega t)$.

We can re-write the problem as
$$
    y_1 = x, \\
	\frac{d y_1}{dt} = y_2, \\
	\frac{d y_2}{dt} = \frac{d^2 x}{dt^2} = -\omega^2 x = -\omega^2 y_1.
$$

$$
    {\bf y}(t) = \left( y_1(t) \atop y_2(t) \right) = \left( x(t) \atop \quad \frac{dx(t)}{dt} \right)  \\
    \frac{d}{dt} { \bf y}(t) = \left( \frac{d y_1}{dt} \atop \frac{d y_2}{dt} \right) = \left( y_2 \atop -\omega^2 y_1 \right) 
$$

The initial condition
$$
    {\bf y}(0) = \left( x(0) \atop \quad \frac{dx(0)}{dt} \right) = \left(1 \atop 0\right).
$$

## Numerical methods for solving the IVP for ODEs:

* Explicit
* Implicit
* Predictor-corrector
* Geometric integrator
* Adaptive step size

## Explicit Euler's method

Using the forward finite difference (see Module 1), we obtaine

$$
    {\bf y}_{k + 1} = {\bf y}_k + {\bf f}({\bf y}_k, t_k) \Delta t + O(\Delta t^2), \qquad
    k=0,1,2, \ldots,
$$

where the time lattice $t_k = k \Delta t$, ${\bf y}_k = {\bf y}(t_k)$. Note that ${\bf y}_0$ is the given initial condition.

In [1]:
function explicit_euler(𝐟::Function, 𝐲₀::Vector, T_final::Real, N::Int)
    Δt = T_final / N
    
    # initialization
    𝐲 = zeros(length(𝐲₀), N + 1)
    
    𝐲
    
    return 𝐲
end

explicit_euler (generic function with 1 method)

In [3]:
𝐲₀ = [1; 0]

2-element Vector{Int64}:
 1
 0

In [14]:
𝐲 = rand(length(𝐲₀), 5)

2×5 Matrix{Float64}:
 0.0786861  0.0251389  0.994858   0.583211  0.645824
 0.433663   0.616499   0.0183802  0.210001  0.662628

In [18]:
𝐲[:, 2]

2-element Vector{Float64}:
 0.025138929991734504
 0.6164986130259474

In [9]:
size(𝐲₀)

(2,)

In [ ]:
₀